version: "3"
services:
  db:
    image: mariadb:10.4.1
    env_file:
      - '.env'
  redis:
    image: redis:5.0

  api:
    build: api
    image: l3ku/stockpal-api:0.0.1
    volumes:
      - './api/app:/app/app:rw'
    env_file:
      - '.env'
    links:
      - db
      - redis

  celery:
    build: api
    image: l3ku/stockpal-api:0.0.1
    entrypoint:
      - celery
      - worker
      - -B
      - -l
      - info
      - -A
      - app.tasks
    volumes:
      - './api/app:/app/app:rw'
    env_file:
      - '.env'
    links:
      - redis
      - db

  nginx:
    build: nginx
    image: l3ku/stockpal-nginx:0.0.1
    ports:
      - '127.0.0.1:80:80'
    links:
      - api
      - ui

  ui:
    build: ui
    image: l3ku/stockpal-ui:0.0.1
    volumes:
      - './ui/app/src:/app/src:rw'
      - './ui/app/public:/app/public:rw'
    environment:
      - PORT=4000
