version: "3"
services:
  db:
    image: mariadb:10.4.1
    env_file:
      - '.env'
  redis:
    image: redis:5.0

  api:
    build:
      context: api
      args:
        APP_ENV: 'development'
    image: l3ku/stockpal-api-dev:0.0.1
    volumes:
      - './api/app:/app/app:rw'
    env_file:
      - '.env'
    links:
      - db
      - redis

  celery:
    build:
      context: api
      args:
        APP_ENV: 'development'
    image: l3ku/stockpal-api-dev:0.0.1
    volumes:
      - './api/app:/app/app:rw'
    env_file:
      - '.env'
    environment:
      DEPLOY_ENV: 'celery'
    links:
      - redis
      - db

  nginx:
    build:
      context: nginx
      args:
        APP_ENV: 'development'
    image: l3ku/stockpal-nginx-dev:0.0.1
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
    links:
      - api
      - ui

  certbot:
    image: certbot/certbot

  ui:
    build:
      context: ui
      args:
        APP_ENV: 'development'
    image: l3ku/stockpal-ui-dev:0.0.1
    volumes:
      - './ui/app/src:/app/src:rw'
      - './ui/app/public:/app/public:rw'
    environment:
      - PORT=4000
