version: "3"
services:
  api:
    build: api
    image: l3ku/stockpal-api:0.0.1
    volumes:
      - './api/app:/app/app:rw'
    env_file:
      - '.env'

  nginx:
    build: nginx
    image: l3ku/stockpal-nginx:0.0.1
    ports:
      - '127.0.0.1:8080:80'
    links:
      - api
      - ui

  ui:
    build: ui
    image: l3ku/stockpal-ui:0.0.1
    volumes:
      - './ui/app/src:/app/src:rw'
    environment:
      - PORT=4000
