// Table data actions
export const REQUEST_ITEMS = 'REQUEST_ITEMS';
export const RECEIVE_ITEMS = 'RECEIVE_ITEMS';
export const REQUEST_ITEMS_ERROR = 'REQUEST_ITEMS_ERROR';
export const RECEIVE_ITEMS_ERROR = 'RECEIVE_ITEMS_ERROR';
export const CHANGE_PAGE = 'CHANGE_PAGE';
export const CHANGE_ITEMS_PER_PAGE = 'CHANGE_ITEMS_PER_PAGE';
export const TOGGLE_SELECTED_ITEMS = 'TOGGLE_SELECTED_ITEMS';
export const RESET_SELECTED_ITEMS = 'RESET_SELECTED_ITEMS';
export const REQUEST_ACTION_ON_ITEMS = 'REQUEST_ACTION_ON_ITEMS';
export const RECEIVE_ACTION_ON_ITEMS = 'RECEIVE_ACTION_ON_ITEMS';
export const REQUEST_ACTION_ON_ITEMS_ERROR = 'REQUEST_ACTION_ON_ITEMS_ERROR';
export const RECEIVE_ACTION_ON_ITEMS_ERROR = 'RECEIVE_ACTION_ON_ITEMS_ERROR';
export const SEARCH_ITEMS = 'SEARCH_ITEMS';


// Authentication actions
export const REQUEST_AUTHENTICATION_LINK = 'REQUEST_AUTHENTICATION_LINK';
export const RECEIVE_AUTHENTICATION_LINK = 'RECEIVE_AUTHENTICATION_LINK';
export const RECEIVE_AUTHENTICATION_LINK_ERROR = 'RECEIVE_AUTHENTICATION_LINK_ERROR';
export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const RECEIVE_LOGIN = 'RECEIVE_LOGIN';
export const REQUEST_LOGIN_ERROR = 'REQUEST_LOGIN_ERROR';
export const RECEIVE_LOGIN_ERROR = 'RECEIVE_LOGIN_ERROR';
export const REQUEST_LOGOUT = 'REQUEST_LOGOUT';
export const RECEIVE_LOGOUT = 'RECEIVE_LOGOUT';
export const RECEIVE_LOGOUT_ERROR = 'RECEIVE_LOGOUT_ERROR';
export const INVALIDATE_LOGIN = 'INVALIDATE_LOGIN';

// User actions
export const REQUEST_USER_INFO = 'REQUEST_USER_INFO';
export const RECEIVE_USER_INFO = 'RECEIVE_USER_INFO';
export const RECEIVE_USER_INFO_ERROR = 'RECEIVE_USER_INFO_ERROR';