// Stock actions
export const REQUEST_STOCKS = 'REQUEST_STOCKS';
export const RECEIVE_STOCKS = 'RECEIVE_STOCKS';
export const RECEIVE_STOCKS_ERROR = 'RECEIVE_STOCKS_ERROR';
export const REQUEST_GAINER_STOCKS = 'REQUEST_GAINER_STOCKS';
export const RECEIVE_GAINER_STOCKS = 'RECEIVE_GAINER_STOCKS';
export const RECEIVE_GAINER_STOCKS_ERROR = 'RECEIVE_GAINER_STOCKS_ERROR';
export const REQUEST_USER_STOCKS = 'REQUEST_USER_STOCKS';
export const RECEIVE_USER_STOCKS = 'RECEIVE_USER_STOCKS';
export const RECEIVE_USER_STOCKS_ERROR = 'RECEIVE_USER_STOCKS_ERROR';

// Authentication actions
export const REQUEST_AUTHENTICATION_LINK = 'REQUEST_AUTHENTICATION_LINK';
export const RECEIVE_AUTHENTICATION_LINK = 'RECEIVE_AUTHENTICATION_LINK';
export const RECEIVE_AUTHENTICATION_LINK_ERROR = 'RECEIVE_AUTHENTICATION_LINK_ERROR';
export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const RECEIVE_LOGIN = 'RECEIVE_LOGIN';
export const REQUEST_LOGIN_ERROR = 'REQUEST_LOGIN_ERROR';
export const RECEIVE_LOGIN_ERROR = 'RECEIVE_LOGIN_ERROR';
export const REQUEST_LOGOUT = 'REQUEST_LOGOUT';
export const RECEIVE_LOGOUT = 'RECEIVE_LOGOUT';
export const RECEIVE_LOGOUT_ERROR = 'RECEIVE_LOGOUT_ERROR';
export const INVALIDATE_LOGIN = 'INVALIDATE_LOGIN';

// User actions
export const REQUEST_USER_INFO = 'REQUEST_USER_INFO';
export const RECEIVE_USER_INFO = 'RECEIVE_USER_INFO';
export const RECEIVE_USER_INFO_ERROR = 'RECEIVE_USER_INFO_ERROR';