"""empty message

Revision ID: 0dc4170ac858
Revises: 7ca87629c8a8
Create Date: 2019-03-02 22:39:06.550398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dc4170ac858'
down_revision = '7ca87629c8a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_stock',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stock_symbol', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['stock_symbol'], ['stock.symbol'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'stock_symbol')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_stock')
    # ### end Alembic commands ###
