"""empty message

Revision ID: 58f290843931
Revises: 61dfd690b609
Create Date: 2019-01-30 22:15:24.464391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58f290843931'
down_revision = '61dfd690b609'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('o_auth2_token_ibfk_1', 'o_auth2_token', type_='foreignkey')
    op.create_foreign_key(None, 'o_auth2_token', 'logged_in_user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'o_auth2_token', type_='foreignkey')
    op.create_foreign_key('o_auth2_token_ibfk_1', 'o_auth2_token', 'logged_in_user', ['user_id'], ['id'])
    # ### end Alembic commands ###
