"""empty message

Revision ID: 61dfd690b609
Revises: 1c8fdcd0cdd1
Create Date: 2019-01-30 20:28:41.997874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61dfd690b609'
down_revision = '1c8fdcd0cdd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('o_auth2_token', sa.Column('provider', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('o_auth2_token', 'provider')
    # ### end Alembic commands ###
