"""empty message

Revision ID: 7f34c6a5140c
Revises: 0dc4170ac858
Create Date: 2019-04-09 14:16:16.713530

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f34c6a5140c'
down_revision = '0dc4170ac858'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logged_in_user', sa.Column('api_secret', sa.String(length=1000), nullable=False))
    op.drop_index('login_id', table_name='logged_in_user')
    op.create_unique_constraint(None, 'logged_in_user', ['api_secret'])
    op.drop_column('logged_in_user', 'login_secret')
    op.drop_column('logged_in_user', 'login_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logged_in_user', sa.Column('login_id', mysql.VARCHAR(length=200), nullable=False))
    op.add_column('logged_in_user', sa.Column('login_secret', mysql.VARCHAR(length=1000), nullable=False))
    op.drop_constraint(None, 'logged_in_user', type_='unique')
    op.create_index('login_id', 'logged_in_user', ['login_id'], unique=True)
    op.drop_column('logged_in_user', 'api_secret')
    # ### end Alembic commands ###
